# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Restaurera Sverige AB
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# User setting
owner: Restaurera Sverige AB
email: Bengt.Wahlgren@gmail.com
facebook_username:
twitter_username: restaurera
github_username:  restaurera
address:
  - line: Kirsebergsgatan 40, 212 20 Malmö, Sweden
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
